server:
  port: 8080

app:
  mqtt:
    host: tcp://broker.mqtt-dashboard.com
    topicLevel: esiot/waterDepth
  serial:
    baud: 115200
  policy:
    l1: 70.0
    l2: 95.0
    t1Ms: 5000
    t2Ms: 8000
  history:
    n: 60
